population_config:
  cells_x: 10   # To achieve maximum scalability, the grid is built using the number of cells along the X and Y axes,
  cells_y: 10   # as well as the area of a single cell.
  cell_area: 4500 # total area of 450,000 square kilometers
  min_density: 1
  max_density: 5000
  destination_cells: [14]

airports_config:
  num: 40
  min_distance: 30 # km
  min_cost: 1
  max_cost: 10

aircraft_config:
  tau: 400 # single charge range
  cruise_speed: 400 # km per hours

ground_access_config:
  max_time: 90 # min
  avg_speed: 60 # km per hours

paths_config:
  max_edges: 3 # maximum of 3 adjacent edges (maximum of 2 intermediate airports)
  routing_factor_thr: 1.4 # ratio between the pathâ€™s total flight distance and the nonstop flight distance

model_config:
  epsilon: 30
  mu_1: 1
  mu_2: 0.01
  closest_airport_to_destination_cell: True # if True the destination airport will be the closest one to the first
                                            # destination cell. Otherwise, given a set of destination cells the
                                            # destination airports will be the ones within a specified maximum ground
                                            # distance from the destination cell
  lexicographic: True
  mip_gap: 0.000

heuristic_config:
  initial_kernel_size: 5
  bucket_size: 10
  iterations: 3
  max_run_time: 8500

kernel_search: False
random_seed: 5
logging_lvl: 20 # 10: debug; 20: info
print_logs: False
plot: False