# To achieve maximum scalability, the grid is built using the number of cells along the X and Y axes, as well as the
# area of a single cell.
population_config:
  cells_x: 20
  cells_y: 10
  cell_area: 2250 # total area of 450,000 square kilometers
  min_density: 0
  max_density: 50000
  destination_cells: [61]

airports_config:
  num: 10 # 7 is interesting
  min_distance: 30 # km
  min_cost: 1
  max_cost: 1

aircraft_config:
  tau: 400 # single charge range
  cruise_speed: 400 # km per hours

ground_access_config:
  max_time: 90 # min
  avg_speed: 60 # km per hours

paths_config:
  max_edges: 3 # maximum of 3 adjacent edges (maximum of 2 intermediate airports)
  routing_factor_thr: 1.4 # ratio between the pathâ€™s total flight distance and the nonstop flight distance

model_config:
  epsilon: 10
  mu_1: 100
  mu_2: 1000

logging_lvl: 20 # 10: Debug; 20: info
print_logs: True